export { default as Inicio       } from './Home';
export { default as Producto     } from './Products/Product';
export { default as Categoria    } from './Products/Categorie';
export { default as Notificacion } from './Menu/Notification';
export { default as Historial    } from './Menu/PurchaseHistory';
export { default as Login        } from './Sesion/Login';
export { default as Signup       } from './Sesion/SignUp';
export { default as Perfil       } from './Sesion/Perfil';
export { default as Recuperar    } from './Sesion/ChangePassword';
